import * as z from "zod";
import { FieldTypeMappingSchema } from "./field-type-mappings";

export const GeneratorOptsSchema = z.object({
    dryRun: z
        .boolean()
        .nullish(),
    schemaPath: z
        .string()
        .nullish()
        .transform((it) => it ?? "schema.yaml"),
    connectionSourcePath: z
        .string()
        .nullish()
        .transform((it) => it ?? "src/db/connection-source.ts"),
    outputDirPath: z
        .string()
        .nullish()
        .transform((it) => it ?? "src/generated"),
    fieldTypeMappings: FieldTypeMappingSchema
        .array()
        .nullish(),
    commonPrimaryKey: z
        .object({
            name: z.string().nullish(),
            isAutoGenerated: z.boolean().nullish()
        })
        .nullish()
});

export type GeneratorOpts = z.TypeOf<typeof GeneratorOptsSchema>;
